spring.application.name=api-gateway
server.port=8083


eureka.client.enabled=false
spring.cloud.discovery.enabled=false

#AuthService Route

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
# Route 2: Account Service
spring.cloud.gateway.routes[1].id=account-service
spring.cloud.gateway.routes[1].uri=http://account-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/accounts/**
# Optional logging
logging.level.org.springframework.cloud.gateway=INFO
